### PR TITLE
Feature/wketchum read interface updates

### LINKED ISSUE #11: Interface for getting list of geoids from Record
and, getting a list of fragment_ptrs satisfying geoid system type

e.g. (from Pengfei):
`hdf5libs::HDF5RawDataFile::get_component_geoids(const daqdataformats::trigger_number_t trig_num, const daqdataformats::GeoID::SystemType type)`
`hdf5libs::HDF5RawDataFile::get_fragment_ptrs(const daqdataformats::trigger_number_t trig_num, const daqdataformats::GeoID::SystemType type)`

### PR DESCRIPTION
**Pull request by wesketchum**
Draft PR for updating read interfaces.

Fixes #11

### CODE REVIEW

**Comment by wesketchum** [comment]
Also:
* Fixes #20 
* Fixes #21

**Comment by wesketchum** [comment]
This PR will need following:
* daqdataformats: https://github.com/DUNE-DAQ/daqdataformats/pull/23
* dfmodules: https://github.com/DUNE-DAQ/dfmodules/pull/156

And it will need to be updated to be on a patch branch (should be based off of the v2.10.0 version already)

**Comment by dingp** [comment]
* added option for specifying clock speed, default is 50MHz (in both `binary_dump.py` and `hdf5_dump.py`);
* changed the `-p` option to make it repeatable, so that "attributes", "header" and "fragment" is only printed when specified; kept "both" and added "all" option as shortcuts.
* fixed a bug that previously if not using `-n` option, no record will be displayed; this is now changed to print out all records if "-n" is not used.

**Comment by bieryAtFnal** [comment]
Thanks for the fixes/changes, Pengfei.

I noticed the the TriggerRecord separator line seems to be missing with the latest hdf5_dump.py script.  Here is a sample from an old version of the script.  With the new script, the "=========" line is missing.  Could it be brought back?  (For reference, separator lines between Fragments *do* seem to be appearing.

```
Path                          :	TriggerRecord00030/TriggerRecordHeader
Size                          :	(128, 1)
Data type                     :	int8
Magic word                    : 0x33334444
Version                       : 2
Trigger number                : 30
Trigger timestamp             : 79554162220211818 (2020-06-02 02:34:04.404237)
No. of requested components   : 2
Run Number                    : 112
Error bits                    : 0
Trigger type                  : 1
Sequence number               : 0
Max sequence num              : 0
================================================================================
Path                          :	TriggerRecord00031/TriggerRecordHeader
Size                          :	(128, 1)
Data type                     :	int8
Magic word                    : 0x33334444
Version                       : 2
Trigger number                : 31
Trigger timestamp             : 79554162225170428 (2020-06-02 02:34:04.503409)
No. of requested components   : 2
Run Number                    : 112
Error bits                    : 0
Trigger type                  : 1
Sequence number               : 0
Max sequence num              : 0
```

**Comment by bieryAtFnal** [comment]
I noticed that "-p header" with TimeSlice files runs into problems, as shown below.  I included the hostname and path to the TimeSlice file in the console output, if you would like a sample TimeSlice file.

```
(dbt-pyvenv) [biery@mu2edaq13 rundir]$ hdf5_dump.py -p header -f tpstream_run000102_0000_tpwriter_20220325T161427.hdf5 
================================================================================
Path                          :	TimeSlice000001
Size                          :	(24, 1)
Data type                     :	int8
Traceback (most recent call last):
  File "/home/biery/dunedaq/25Mar2.10.1Test/install/hdf5libs/bin/hdf5_dump.py", line 281, in <module>
    main()
  File "/home/biery/dunedaq/25Mar2.10.1Test/install/hdf5libs/bin/hdf5_dump.py", line 273, in main
    h5.printout(args.print_out, args.num_of_records, args.list_components)
  File "/home/biery/dunedaq/25Mar2.10.1Test/install/hdf5libs/bin/hdf5_dump.py", line 65, in printout
    print_header(data_array, self.record_type, self.clock_speed_hz,
  File "/home/biery/dunedaq/25Mar2.10.1Test/install/hdf5libs/bin/hdf5_dump.py", line 208, in print_header
    print_time_slice_header(data_array, clock_speed_hz)
  File "/home/biery/dunedaq/25Mar2.10.1Test/install/hdf5libs/bin/hdf5_dump.py", line 199, in print_time_slice_header
    print_header_dict(unpack_header(data_array[:20], unpack_string, keys))
TypeError: print_header_dict() missing 1 required positional argument: 'clock_speed_hz'
(dbt-pyvenv) [biery@mu2edaq13 rundir]$ pwd
/home/biery/dunedaq/25Mar2.10.1Test/rundir
(dbt-pyvenv) [biery@mu2edaq13 rundir]$ hostname
mu2edaq13
```

**Comment by dingp** [comment]
Thanks for testing on TimeSlice file. I fixed the bug and brought back the line separator, also added description in the line separator.

**Comment by bieryAtFnal** [comment]
Thanks Pengfei for the fixes.  The hdf5_dump.py tests that I've run with the latest changes look good to me.
I've also run regression tests with all of the changes, and those look good.
I'll plan on running some tests at ICEBERG later today as a double-check (mostly to see the new trigger bits being printed out, which I fully expect to work).

**Review by dingp — APPROVED** [review]
The changes look good to me. 

Linting and testing are both passed.

However, I got the following error when testing "HDF5LIBS_TestReader.py". It looks like the GeoID is not comparable. 

```
(dbt-pyvenv) [root@ca4a1501f738 dev]# python3 ./sourcecode/hdf5libs/test/apps/HDF5LIBS_TestReader.py ./tpstream_run000102_0000_tpwriter_20220325T161427.hdf5
File Attribute  application_name  =  tpwriter
File Attribute  closing_timestamp  =  1648224900962
File Attribute  creation_timestamp  =  1648224867049
File Attribute  file_index  =  0
File Attribute  filelayout_params  =  {"digits_for_record_number":6,"digits_for_sequence_number":0,"path_param_list":[{"detector_group_name":"TPC","detector_group_type":"TPC","digits_for_element_number":2,"digits_for_region_number":3,"element_name_prefix":"Link","region_name_prefix":"APA"}],"record_header_dataset_name":"TimeSliceHeader","record_name_prefix":"TimeSlice"}
File Attribute  filelayout_version  =  2
File Attribute  operational_environment  =  swtest
File Attribute  record_type  =  TimeSlice
File Attribute  recorded_size  =  202763952
File Attribute  run_number  =  102
Number of records: 34
Processing record (num,seq):  (1, 0)
/TimeSlice000001/TimeSliceHeader: 1
Traceback (most recent call last):
  File "./sourcecode/hdf5libs/test/apps/HDF5LIBS_TestReader.py", line 101, in <module>
    main()
  File "./sourcecode/hdf5libs/test/apps/HDF5LIBS_TestReader.py", line 68, in main
    for gid in h5_file.get_geo_ids(rid)[:10]:
  File "/scratch/dev/install/hdf5libs/lib64/python/hdf5libs/__init__.py", line 24, in get_geo_ids
    return sorted(super().get_geo_ids(*args,**kwargs))
```

Just saw there's a PR in `daqdataformats` to adding the comparison between GeoIDs in the python module.

The error is gone after using these two PRs together.

**Comment by dingp** [comment]
As part of this review, merged PR DUNE-DAQ/daqdataformats#23

**Comment by dingp** [comment]
Also reviewed/merged: https://github.com/DUNE-DAQ/dfmodules/pull/156

**Comment by dingp** [comment]
I noticed that the "trigger timestamp" field is different in the timeslice file. I am looking into possible changes required for handling it.

```
(dbt-pyvenv) [root@ca4a1501f738 dev]# hdf5_dump.py -f tpstream_run000102_0000_tpwriter_20220325T161427.hdf5 -p fragment -n 1
------------------------------- Fragment Header  -------------------------------
Path                          : TimeSlice000001/TPC/APA000/Link00
Size                          : (364640, 1)
Data type                     : int8
Marker word                   : 0x11112222
Version                       : 3
Frag Size                     : 364640
Trig number                   : 1
Trig timestamp                : 18446744073709551615 (InvalidDateString)
Window begin                  : 79554162065000000 (2020-06-02 07:34:01.300000)
Window end                    : 79554162070000000 (2020-06-02 07:34:01.400000)
Run number                    : 102
Error bits                    : 0
Fragment type                 : 4
Sequence number               : 65535
GeoID type                    : TPC
GeoID region                  : 0
GeoID element                 : 0
-
```

**Review by dingp — APPROVED** [review]

**Review by bieryAtFnal — APPROVED** [review]
LGTM.
At the ICEBERG teststand, I was able to successfully see the clock speed argument to hdf5_dump.py in action, as well as other features.

**Pull request merged**
